### ISSUE TITLE
I can't download ricotta strings after updating ruby gem to 1.8.7 

### ISSUE THREAD

**Issue by solydakim** [eriksundin/ricotta-gem#1]
I have updated my ruby gem to version 1.8.7 (2012-10-12 patchlevel 371) [i686-darwin12] and then I tried to download my localised strings from Ricotta by executing the command 'ricotta install:xcode', but it always failed with following error:

Faraday: you may want to install system_timer for reliable timeouts
invalid command. Use --help for more information
/opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': /o
...n?", *dir_options, none_option)
                              ^
        from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
        from /opt/local/lib/ruby/gems/1.8/gems/ricotta-0.0.2/lib/ricotta/commands.rb:4
        from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original
        from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
        from /opt/local/lib/ruby/gems/1.8/gems/ricotta-0.0.2/bin/ricotta:19
        from /opt/local/bin/ricotta:23:in `load'
        from /opt/local/bin/ricotta:23

**Comment by eriksundin** [comment]
The problem occurs on Ruby version 1.8.7, which is the system default currently on Mac OSX.
It was an unsupported syntax that caused it. Fixed in version 0.0.3 of the gem. Just do a 'gem install ricotta' to get the latest version.
